service: ev-dashboard-api
frameworkVersion: '2'

plugins:
  - serverless-api-gateway-caching

custom:
  apiGatewayCaching:
    enabled: true
    clusterSize: '0.5'
    ttlInSeconds: 300
    dataEncrypted: false
    perKeyInvalidation:
      requireAuthorization: true # default is true
      handleUnauthorizedRequests: Ignore # default is "IgnoreWithWarning".

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  apiGateway:
    shouldStartNameWithService: true

  stage: v1
  region: eu-west-2

functions:
  exchange:
    handler: handler.exchange
    environment:
      SMARTCAR_CLIENT_ID: ea125c5b-bda1-41a6-a33f-e1c0c9c33779
      SMARTCAR_CLIENT_SECRET: ${ssm:/ev-dashboard-secret-key~true}
      SMARTCAR_REDIRECT_URI: https://javascript-sdk.smartcar.com/v2/redirect?app_origin=https://d17f0ehhxwd38n.cloudfront.net
      #SMARTCAR_REDIRECT_URI: https://javascript-sdk.smartcar.com/v2/redirect?app_origin=http://localhost:3000
    events:
      - http:
          path: /exchange
          method: get
          cors: true
  vehicle:
    handler: handler.vehicle
    events:
      - http:
          path: /vehicle
          method: get
          cors: true
          caching:
            enabled: true
            cacheKeyParameters:
              - name: request.querystring.accessToken
